# Generated by Django 4.0.5 on 2022-07-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'em_andamento'), ('iniciada', 'iniciada'), ('concluida', 'concluida')], default='em andamento', max_length=12),
        ),
    ]
