# Generated by Django 4.0.5 on 2022-07-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'em_andamento'), ('pendente', 'pendente'), ('concluida', 'concluida')], default='em andamento', max_length=12),
        ),
    ]
