# Generated by Django 4.0.5 on 2022-07-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(default='baixa', max_length=6),
        ),
    ]
