# Generated by Django 4.0.5 on 2022-07-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('em andamento', 'em andamento'), ('pendente', 'pendente'), ('concluída', 'concluída')], default='em andamento', max_length=12),
        ),
    ]
